### ISSUE TITLE
Changelog Support

### ISSUE THREAD

**Issue by stephenmac7** [PackAssembler/PackAssembler#19]
Allow changelogs to be associated with mod versions. Deletions should merge the changelog with the successive version. If no successive version exists, the changelog is lost.

**Comment by ZL1LAC** [comment]
Should get on to this.

**Comment by XCompWiz** [comment]
Even being able to attach links to a mod version entry would allow for links to changelogs elsewhere, which would probably work best for a number of cases.  Better to link to the existing changelogs made by the devs than to rely on some form of text logs created while uploading.  Less work for you, too.

**Comment by stephenmac7** [comment]
That's true. It's definitely a better way to do it, also making it easier to implement.
