### ISSUE TITLE
Permission Link Required and Prominent

### ISSUE THREAD

**Issue by XCompWiz** [PackAssembler/PackAssembler#24]
Please make it so that a link to the relevant permission information is a must for mod entries.  This would link to the text/page which says why/how you are allowed to distribute the mod.
You may need to move permission from a mod level entry to a download item property (This would allow for permissions to individual versions of mods).

This will help regulate permissions so you don't wind up in error.

Additionally, make the permission link more prominent.  Currently it's buried and hidden at the bottom.  It's certainly more important than when it was added to your database, so why is that in the top section and permission info hidden?

Once these issues are resolved I'll permit the distribution of Mystcraft via this system. :)  Looking forward to it, as this is a system I think we've needed for a while.

**Comment by ZL1LAC** [comment]
Hey @XCompWiz what does Prominent mean?

**Comment by stephenmac7** [comment]
I'm not sure about required, since there are edge cases including the author maintaining their own mod and the direct linking (as there are technically three ways to register a version: upload, upload from url, and direct linking to url, which is not recommended). Per mod permission, though, is a burden on maintaining versions. I will, however, clearly mark directly linked versions now.

**Comment by XCompWiz** [comment]
@DH47 Big and obvious.

@stephenmac7 Direct linking isn't something you should be doing at all (except with permission), as your direct linking looks like a normal download from the user perspective and there's no difference between that and hosting it...

Prominent is probably enough, so long as SOMETHING indicates that you have permissions. :) I'll be checking before I upload Mystcraft.

**Comment by stephenmac7** [comment]
If you check the version table now, direct links have been made obvious and
put in red. The FAQ also discourages use except as a last resort.
