### ISSUE TITLE
Dependency for mods 

### ISSUE THREAD

**Issue by Isaac-Wheeler** [PackAssembler/PackAssembler#7]

**Comment by stephenmac7** [comment]
Okay, for now I'm not adding version number restrictions on dependencies. However, I do have the dependency system in place (on the mods side). Now how do you think I should enforce it?

**Comment by Isaac-Wheeler** [comment]
i would just have the Contributor add the dependencies in maybe a dropdown list that they just select from

**Comment by stephenmac7** [comment]
It's not finished yet. I'm still working on showing dependencies and enforcing them.
