### ISSUE TITLE
Testing not complete

### ISSUE THREAD

**Issue by stephenmac7** [PackAssembler/PackAssembler#9]
Some testing is missing, finish writing tests.

**Comment by ZL1LAC** [comment]
Close this seems not needed anymore?

**Comment by stephenmac7** [comment]
Actually, we still need to make sure everything works.

**Comment by ZL1LAC** [comment]
If something is wrong then a separate issue should be created.

**Comment by stephenmac7** [comment]
Yes, but this not being finished is something wrong. It's actual code that should be there but isn't.
